version: '3.9'

services:
  mongodb:
    build: ./db
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - backend-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/whatdoweeat
    networks:
      - backend-network
      - frontend-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - frontend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

