name: Build and push docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-push-backend-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Backend Docker Image
      run: |
        cd backend
        docker build -t samuelholmes/whatdoweeat-backend:latest .
        docker push samuelholmes/whatdoweeat-backend:latest


  build-push-frontend-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      run: |
        cd frontend
        docker build -t samuelholmes/whatdoweeat-frontend:latest .
        docker push samuelholmes/whatdoweeat-frontend:latest
  
  build-push-db-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push db Docker Image
      run: |
        cd db
        docker build -t samuelholmes/whatdoweeat-db:latest .
        docker push samuelholmes/whatdoweeat-db:latest
